AllCops:
  Exclude:
    - 'db/schema.rb'

Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Max: 99999

Metrics/MethodLength:
  Max: 50

Style/Encoding:
  Enabled: true
  EnforcedStyle: when_needed
